kname: Deploy Laravel Aimeos to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'

            cd ~/myshop

            echo "Pull code..."
            git pull origin main > /dev/null 2>&1

            echo "Start docker..."
            docker-compose up -d --build > /dev/null 2>&1

            echo "Migration..."
            docker exec laravel_app php artisan migrate --force > /dev/null 2>&1

            echo "Aimeos setup..."
            docker exec laravel_app php artisan aimeos:setup --force > /dev/null 2>&1

            echo "Clear cache..."
            docker exec laravel_app php artisan config:clear > /dev/null 2>&1
            docker exec laravel_app php artisan cache:clear > /dev/null 2>&1

            echo "DONE 🚀"

          EOF
